she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('story/<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('story/<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, AccountView, EditUserProfileView, AuthorsView


app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>', AccountView.as_view(), name='profile'),
    path('view-authors', AuthorsView.as_view(), name='authors'),
    path('edit-profile/', EditUserProfileView.as_view(), name='editProfile'),

]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

class Category(models.Model):
    category_name = models.CharField(max_length=25)
    def __str__(self):
        return self.category_name

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name = 'posts'
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(default="https://picsum.photos/600")
    newsCategory = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title
    

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username


# class profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     #image
#     def __str__(self):
#         return f'Hello {self.user.username}, welcome to your profile'
    
# Create your models here.

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content','image','newsCategory']
        #labels = { 'image: ('image URL'}
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
            }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class EditUserProfileForm(forms.ModelForm):
    email = forms.EmailField(max_length=254, help_text='Required. Valid email address required.')

    class Meta:
        model = CustomUser
        fields = ['username','email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory, Category
from .forms import StoryForm
from django.shortcuts import render
from django.views.generic.edit import DeleteView, UpdateView


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.order_by('?')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EditStoryView(UpdateView):
    model = NewsStory
    template_name = 'news/editStory.html'
    fields = ['title', 'pub_date', 'content','image','newsCategory']
    success_url = reverse_lazy('news:index')

class DeleteStoryView(DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')


class CategoryView(generic.ListView):
    template_name = 'news/categoryView.html'

    def get_queryset(self):
        '''Return category'''
        return Category.objects.all()
    
    def get_context_data(self, **kwargs):
        cont = super().get_context_data(**kwargs)
        cont['selected_category'] = Category.objects.order_by('-pub_date')[:4]
        return cont

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from django.shortcuts import render
from news.models import NewsStory
from django.views.generic.edit import CreateView, FormView, UpdateView
from .forms import CustomUserCreationForm, EditUserProfileForm
from django.views.generic import ListView

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/createAccount.html'


class AccountView(generic.DetailView):
    model = CustomUser
    template_name = 'registration/profile.html'
    context_object_name = 'user'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
        return context

class EditUserProfileView(UpdateView):
    form_class = EditUserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'registration/editProfile.html'
    
    def get_success_url(self):
        print(self.request.user.id)
        print(type(self.get_form()))
        return reverse_lazy('users:profile', kwargs={"pk":self.request.user.id})

    def get_object(self):
        return self.request.user


class AuthorsView(ListView):
    model = CustomUser
    template_name = 'users/viewAuthors.html'
    # context_object_name = 'author'

    def get_queryset(self):
        return CustomUser.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = CustomUser.objects.all()
        return context



# def register(request):
#     data = {
#         'form': CustomUserCreationForm()
#     }
#     return render(request, 'registration/register.html', data)


# def profile(request):
#     return render(request, 'registration/profile.html')

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% block content %}

<form id="newstoryform" action="" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">

</form>

{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends 'base.html' %}
{% block title %} Delete Post {% endblock %}
{% block content %}

<div>
    <h2> You want to delete: {{ newsstory.title }} ?</h2>

    <div>
       <form method="POST">
        {% csrf_token %}
        <button>Delete Post</button>
    </div>


</div>

{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends 'base.html' %}
{% block content %}

    <h2> Edit Your Post ✏️</h2>
   
    <div>
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Edit Post</button>
    </div>




{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<a href="{% url 'news:newStory' %}">Write New Story</a>
{% endif %}



    <h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
        
{% endblock %}  
    
    
    
    
    

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4>Author: {{ story.author }}</h4>
        <h4>Category: {{ story.newsCategory }}</h4>
        <div id="story-content">
            <img src="{{ story.image }}">
            {{ story.content|linebreaks }}
        </div>
    </div>




<div class="story-buttons">
        {% if request.user.id == story.author.id %}
            <a id="edit-delete-buttons" href="{% url 'news:editStory' story.pk %}">Edit Story</a> <br/>
            <a id="edit-delete-buttons" href="{% url 'news:deleteStory' story.pk %}">Delete</a> <br/>
        {% else %}
        {% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            <img src="{{ story.image }}">
        {% else %}
            <img src="{{ story.image }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
            <h4>{{ story.newsCategory }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
            {% block stylesheets %}{% endblock %}
    </head>

    <body>
    <header>
        <div id="header-text">
            <a id="header-link" href="{% url 'news:index' %}">
                <h1>She {Codes} News</h1>
            </a>
        </div>
        {% include './nav.html' %}
    </header>
    {% block content %}{% endblock %}
        <!-- content blocks here -->
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'users:profile' request.user.id %}">{{ user.username }}</a>
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>